GET http://localhost:5000/user


###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "name": "user",
    "email": "user@gmail.com",
    "password": "tacongduc"
}


###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "tacongduc"
}


###
GET http://localhost:5000/user/infor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDliNjkxODNhYjE0OGUwMDc3MDNiZSIsImlhdCI6MTY0MjU4NDkxOCwiZXhwIjoxNjQyNjcxMzE4fQ.uogDmQsn-mSTTizALXzHSmXeasDkwohhmfwLc4lQvFg

###
GET http://localhost:5000/user/refresh_token

###
GET http://localhost:5000/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDliNjkxODNhYjE0OGUwMDc3MDNiZSIsImlhdCI6MTY0MjY4OTQ4NSwiZXhwIjoxNjQyODYyMjg1fQ.i7NzKvqkcQe4XHHCVk0vuPdqwjGghcDAx3RCyRwx6O0