GET http://localhost:5000/user


###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "tacongduc"
}


###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "tacongduc"
}


###
GET http://localhost:5000/user/infor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDY3MGM2MTE5YWExODg0NjU3MGFhZSIsImlhdCI6MTY0MTQ3ODk5OCwiZXhwIjoxNjQxNTY1Mzk4fQ.YprZf7FURSi9PP9nqxVcSH58v052Pd7ebsXemg_bqZ4
