GET http://localhost:5000/api/product
###

GET http://localhost:5000/api/product?price=120

###create
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "product_id": "pr02",
    "title":"Oneplus",
    "price": 100,
    "description": "Description oneplus",
    "content": "Oneplus Content",
    "images": {
        "public_id": "Mern/oeqpjmbdltyinuyhamen",
        "url": "https://res.cloudinary.com/dzoav55s4/image/upload/v1641737469/Mern/oeqpjmbdltyinuyhamen.png"
    },
    "category": "Smartphone"
}

###

POST http://localhost:5000/api/payment